/**
 * skillForge.ts — Core forge_skill logic
 *
 * APEX THEORY Epoch 34Ω — Organism Layer
 *
 * The forge loop:
 *   1. arifOS judges → SEAL
 *   2. A-FORGE asks: do I have a tool for this?
 *      ├── YES → forge_execute (existing)
 *      └── NO  → forge_skill (generate)
 *                  ├── LLM generates tool code
 *                  ├── Layer 1: HARAM scan
 *                  ├── Layer 2: Decision Field G = Q·V·Ψ·Φ
 *                  ├── Layer 3: Scar Law consultation
 *                  ├── Layer 4: VAULT999 seal (if SEAL verdict)
 *                  ├── Register to SkillRegistry
 *                  └── Optional: execute (requires seal_verdict_id)
 */

import crypto from "node:crypto";
import { promises as fs } from "node:fs";
import { computeDecisionField } from "./decisionField.js";
import { consultScars, fingerprintIntent, sealScar } from "./scarLaw.js";
import { getSkillRegistry } from "./skillRegistry.js";
import type { ForgeSkillRequest, ForgeSkillResult, SkillManifest } from "./types.js";

const RUNTIME_DIR = "/root/A-FORGE/.runtime/skills/";
const SCAR_PATTERNS: Array<{ re: RegExp; severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW"; name: string }> = [
  { re: /rm\s+-rf\s+\/\s*(;|$|\||2>)/, severity: "CRITICAL", name: "rm -rf /" },
  { re: /DROP\s+DATABASE|DROP\s+TABLE/i, severity: "CRITICAL", name: "DROP DATABASE/TABLE" },
  { re: /:\(\)\s*\{\s*:\|:&\s*\;?\s*\};?\s*:/, severity: "CRITICAL", name: "Fork bomb" },
  { re: />\s*\/dev\/(sda|sdb|nvme|mmc)/, severity: "CRITICAL", name: "Direct block device write" },
  { re: /mkfs\.\w+/, severity: "HIGH", name: "Filesystem creation" },
  { re: /dd\s+if=/, severity: "HIGH", name: "dd destructive" },
  { re: /chmod\s+777/, severity: "MEDIUM", name: "World-writable file" },
  { re: /eval\s*\(/, severity: "HIGH", name: "eval() usage" },
  { re: /process\.env\./, severity: "LOW", name: "Environment variable access" },
  { re: /child_process\.exec(File)?\(/, severity: "MEDIUM", name: "Shell exec" },
];

export type LlmProviderLike = {
  generate(opts: { prompt: string; maxTokens?: number; temperature?: number }): Promise<string>;
};

/**
 * Scan implementation for HARAM patterns.
 * Returns count + names of findings.
 */
export function haramScan(implementation: string): { findings: number; names: string[]; critical: number; high: number } {
  const findings: string[] = [];
  let critical = 0;
  let high = 0;
  for (const p of SCAR_PATTERNS) {
    if (p.re.test(implementation)) {
      findings.push(p.name);
      if (p.severity === "CRITICAL") critical++;
      if (p.severity === "HIGH") high++;
    }
  }
  return { findings: findings.length, names: findings, critical, high };
}

/**
 * LLM code generation — produces a TypeScript tool implementation
 * matching a strict schema.
 */
async function generateToolCode(llm: LlmProviderLike, req: ForgeSkillRequest): Promise<{
  tool_name: string;
  description: string;
  input_schema: string;
  implementation: string;
}> {
  const prompt = `You are forge_skill, the constitutional meta-tool of A-FORGE.

Generate a TypeScript MCP tool for the following intent.

INTENT: ${req.intent}
DOMAIN: ${req.domain}
${req.target_tool_name ? `SUGGESTED NAME: ${req.target_tool_name}` : ""}

CONSTRAINTS (constitutional — must respect):
- Tool name MUST start with "forge_"
- Pure computation only — no filesystem mutation, no network calls outside MCP, no shell exec
- Read-only or computation tools only (Phase 1)
- HARAM patterns FORBIDDEN: rm -rf /, DROP DATABASE, fork bombs, /dev/sdX writes, eval(), mkfs, dd if=, chmod 777
- Must export an async function: async (args) => Promise<{ content: Array<{ type: "text", text: string }> }>
- Input must be a JSON-serializable object
- Output must include _epistemic envelope

Return ONLY valid JSON in this exact shape:
{
  "tool_name": "forge_xxx",
  "description": "one-line description",
  "input_schema": "{ zod schema as TypeScript source }",
  "implementation": "async function implementation as TypeScript source"
}

Do NOT include markdown. Do NOT include explanations. ONLY the JSON.`;

  const response = await llm.generate({ prompt, maxTokens: 2000, temperature: 0.2 });

  // Parse — robust against LLM quirks
  let parsed: any;
  try {
    // Try direct parse
    parsed = JSON.parse(response);
  } catch {
    // Try extracting JSON block
    const match = response.match(/\{[\s\S]*\}/);
    if (!match) {
      throw new Error(`LLM did not return valid JSON: ${response.slice(0, 200)}`);
    }
    parsed = JSON.parse(match[0]);
  }

  return {
    tool_name: parsed.tool_name ?? req.target_tool_name ?? "forge_generated",
    description: parsed.description ?? "Generated by forge_skill",
    input_schema: parsed.input_schema ?? "{}",
    implementation: parsed.implementation ?? "async () => ({ content: [{ type: 'text', text: '{}' }] })",
  };
}

/**
 * Main forge entry point.
 */
export async function forgeSkill(
  llm: LlmProviderLike | null,
  req: ForgeSkillRequest,
): Promise<ForgeSkillResult> {
  // Step 0: Irreversible domain gate — F13 SOVEREIGN
  const irreversibleDomains = ["arifos"];
  if (irreversibleDomains.includes(req.domain) && !req.seal_verdict_id) {
    return {
      status: "HOLD",
      decision_field: { Q: 0, V: 0, Psi: 0, Phi: 0, G: 0, verdict: "HOLD", rationale: [] },
      scars_consulted: 0,
      haram_findings: 0,
      message: `F13 SOVEREIGN: domain '${req.domain}' requires seal_verdict_id from arifOS`,
    };
  }

  // Step 1: Consult Scar Law — what failures should constrain this generation?
  const scars = await consultScars(req.intent, req.domain);

  // Step 2: LLM generation (if available)
  let tool_name: string;
  let description: string;
  let input_schema: string;
  let implementation: string;

  if (llm) {
    try {
      const generated = await generateToolCode(llm, req);
      tool_name = generated.tool_name;
      description = generated.description;
      input_schema = generated.input_schema;
      implementation = generated.implementation;
    } catch (err) {
      // LLM failure → seal as scar, return HOLD
      await sealScar({
        intent: req.intent,
        domain: req.domain,
        failure_mode: `LLM generation failed: ${(err as Error).message?.slice(0, 200)}`,
        severity: "MEDIUM",
      });
      return {
        status: "HOLD",
        decision_field: { Q: 0, V: 0, Psi: 0, Phi: 0, G: 0, verdict: "HOLD", rationale: [`LLM generation failed: ${(err as Error).message}`] },
        scars_consulted: scars.length,
        haram_findings: 0,
        message: `LLM generation failed: ${(err as Error).message}. Scar sealed.`,
      };
    }
  } else {
    // No LLM — return template scaffold
    tool_name = req.target_tool_name ?? "forge_generated";
    description = `[TEMPLATE] ${req.intent}`;
    input_schema = "z.object({}).strict()";
    implementation = `async () => ({ content: [{ type: "text", text: JSON.stringify({ status: "TEMPLATE_NO_LLM", intent: ${JSON.stringify(req.intent)} }) }] })`;
  }

  // Step 3: HARAM scan
  const scan = haramScan(implementation);

  // Step 4: Decision Field
  const field = computeDecisionField({
    intent: req.intent,
    domain: req.domain,
    targetToolName: tool_name,
    haramFindings: scan.findings,
    implementation,
    scars,
  });

  // Step 5: Verdict routing
  if (field.verdict === "VOID") {
    // Seal scar — this failure pattern must not repeat
    await sealScar({
      intent: req.intent,
      domain: req.domain,
      failure_mode: `VOID verdict: ${field.rationale.slice(0, 3).join("; ").slice(0, 200)}`,
      severity: "HIGH",
    });
    return {
      status: "VOID",
      tool_name,
      decision_field: field,
      scars_consulted: scars.length,
      haram_findings: scan.findings,
      message: `VOID: ${field.rationale[field.rationale.length - 1] ?? "insufficient energy"}`,
    };
  }

  if (field.verdict === "HOLD") {
    return {
      status: "HOLD",
      tool_name,
      decision_field: field,
      scars_consulted: scars.length,
      haram_findings: scan.findings,
      message: `HOLD: ${field.rationale[field.rationale.length - 1] ?? "defer"}`,
    };
  }

  // Step 6: For SEAL/SABAR — register to SkillRegistry
  const registry = getSkillRegistry();
  const fingerprint = crypto
    .createHash("sha256")
    .update(fingerprintIntent(req.intent, req.domain) + "::" + implementation.trim())
    .digest("hex")
    .slice(0, 16);

  const now = Date.now();
  const expiresAt = new Date(now + 24 * 60 * 60 * 1000).toISOString(); // 24h

  const manifest: SkillManifest = {
    tool_name,
    description,
    domain: req.domain,
    input_schema,
    implementation,
    haram_findings: scan.findings,
    haram_passed: scan.findings === 0,
    decision_field: field,
    scar_pressure_applied: scars.reduce((s, x) => s + x.scar_pressure, 0),
    fingerprint,
    created_at: new Date(now).toISOString(),
    expires_at: expiresAt,
    created_by: req.actor_id,
    status: field.verdict === "SEAL" ? "REGISTERED" : "PENDING_REVIEW",
    execution_count: 0,
  };

  const reg = await registry.register(manifest);
  if (!reg.accepted) {
    return {
      status: "HOLD",
      tool_name,
      decision_field: field,
      scars_consulted: scars.length,
      haram_findings: scan.findings,
      message: `Registration refused: ${reg.reason}`,
    };
  }

  // Step 7: VAULT999 seal — required for Phase 1
  let vaultSealId: string | undefined;
  try {
    vaultSealId = await sealToVault(manifest, field, req);
  } catch (err) {
    // Seal failure → revoke registration
    await registry.revoke(tool_name);
    return {
      status: "HOLD",
      tool_name,
      decision_field: field,
      scars_consulted: scars.length,
      haram_findings: scan.findings,
      message: `VAULT999 seal failed: ${(err as Error).message}. Registration revoked.`,
    };
  }

  manifest.vault_seal_id = vaultSealId;
  await registry.update(manifest);

  return {
    status: field.verdict === "SEAL" ? "SEAL" : "SABAR",
    tool_name,
    fingerprint,
    decision_field: field,
    scars_consulted: scars.length,
    haram_findings: scan.findings,
    vault_seal_id: vaultSealId,
    expires_at: expiresAt,
    message: `${field.verdict}: ${tool_name} forged. Fingerprint=${fingerprint}. Expires=${expiresAt}.`,
  };
}

/**
 * Seal the generated tool to VAULT999.
 * Phase 1: write a record file in .runtime/vault/seals/
 * Phase 2: use proper VAULT999 client.
 */
async function sealToVault(
  manifest: SkillManifest,
  field: import("./types.js").DecisionField,
  req: ForgeSkillRequest,
): Promise<string> {
  const SEAL_DIR = "/root/A-FORGE/.runtime/vault/seals/";
  await fs.mkdir(SEAL_DIR, { recursive: true });
  const sealId = `seal_${Date.now()}_${crypto.randomBytes(4).toString("hex")}`;
  const sealPath = `${SEAL_DIR}${sealId}.json`;
  const sealRecord = {
    seal_id: sealId,
    sealed_at: new Date().toISOString(),
    actor_id: req.actor_id,
    seal_verdict_id: req.seal_verdict_id,
    tool_name: manifest.tool_name,
    fingerprint: manifest.fingerprint,
    domain: manifest.domain,
    decision_field: field,
    haram_findings: manifest.haram_findings,
    scar_pressure_applied: manifest.scar_pressure_applied,
    expires_at: manifest.expires_at,
    schema_version: "1.0.0",
  };
  await fs.writeFile(sealPath, JSON.stringify(sealRecord, null, 2));
  return sealId;
}